### ISSUE TITLE
Feature Request: Generate multiple incorrect answers for questions

### ISSUE THREAD

**Issue by Quixomatic** [sottenad/jService#16]
Hello, I'm building a relatively extensive study platform and am going to be building a data scraping API to gather and generate correct and incorrect answers to questions.

I was wondering if you have any thoughts on this and whether or not your service could be modified to provide 1 correct answer per question as well as a few incorrect ones as well (based on the context of the question).

**Comment by sottenad** [comment]
So, just getting to this now after 2 years :(
I have given tons of thought to how this could be modified to provide incorrect answers as well. There are some questions that are answered incorrectly by the contestants. These are likely very "high quality" incorrect answers, and could be fed into some other API to find other "terms" that are similar. However for the majority of questions that are answered correctly on a single answer, I am not sure there is enough data to feed another service to get back reasonably valid responses. The context of the question is just too important.

Perhaps mechnical turk or some other human-based solution would work, unless there are any hardcore language recognition or machine learning folks that would want to take a stab at this. 

Unfortunately I dont think I have the resources to commit to something like.

FWIW, if you're even still interested in this, I am going to be releasing a new version of jservice with the incorrect answers included on the question, which could serve as a good starting point. Look for something in the next month or two.
