### ISSUE TITLE
Add count parameter to /clues method

### ISSUE THREAD

**Issue by JoshuaPotter** [sottenad/jService#17]

**Comment by AHiggins98** [comment]
How to pass options in the api request?

**Comment by HP4k1h5** [comment]
AHiggins98 you can append `/?value=500` to the url `http://jservice.io/api/clues`
to get for instance : `http://jservice.io/api/clues/?value=500` 
i'm not sure what format the dates are supposed to be in for the min/max_date options

**Comment by AHiggins98** [comment]
Wow thank you so much for getting back to me, I forgot about this!
