### ISSUE TITLE
Trouble fetching from API

### ISSUE THREAD

**Issue by blim8183** [sottenad/jService#2]
Would it be possible to enable CORs on the jService API? I'm having trouble accessing the API.

I think something like rack-cors (https://github.com/cyu/rack-cors) would do the trick.

**Comment by sottenad** [comment]
You should be able to make cross domain calls to the api, although its meant more for you to stand up your own copy that you can run locally or host on your own. The API at jservice.io is for illustrative purposes and hacking together quick projects not intended for others. See http://codepen.io/anon/pen/QydRpr for an example of the most basic usage.
