### ISSUE TITLE
[Feature Request] Add Final Jeopardy question endpoint

### ISSUE THREAD

**Issue by Shugabuga** [sottenad/jService#23]
I am working on an app that would benefit from a Final Jeopardy endpoint. Is there a way to accomplish this currently? If not, could this be implemented as its own API endpoint (like `/final`)?

**Comment by Shugabuga** [comment]
Bump.

**Comment by sottenad** [comment]
Hi, I am not actively maintaining this project anymore. Feel free to submit a pull request and I'll accept it. 
Thanks
Steve

**Comment by sottenad** [comment]
Fixed with 42bad3ee5a86de045f05b72e808166a8b2320901
