### ISSUE TITLE
[Question] Is there any definition on the range of Jeopardy questions?

### ISSUE THREAD

**Issue by matgrioni** [sottenad/jService#25]
I am wanting to use this to quiz myself, but would like to know where exactly the data is coming from and how frequently the underlying data for the service is updated (every show, every week, etc). Any clarification would be appreciated!

**Comment by sottenad** [comment]
Hi,
The project scrapes the jarchive.com site. I leave the jservice.io service running as an example and scrape it every year or so. If you want a more frequent schedule, I would suggest hosting your own instance and automating the scraping. Just do the folks at jarchive a favor and dont fetch all 32 seasons every time :)

**Comment by matgrioni** [comment]
Hi,

Thanks for the response. I wanted to do some more systematic testing without a random element so I will follow your suggestion and have my own scraped data.
