### ISSUE TITLE
API Response for 'Invalid' Endpoint

### ISSUE THREAD

**Issue by rysady** [sottenad/jService#30]
Is there an example payload that's returned from the /api/invalid endpoint?  I don't want to mark a clue invalid just to see what the APIs response is.  Or if there's a specific clue id that we can mark invalid solely for testing purposes?

**Comment by oddluck** [comment]
It will return a 200 OK response, and the response body will include the question content with the increased invalid count, for example:

{"invalid_count":1,"id":128381,"answer":"Father Time","question":"It\'s the personification seen here","value":600,"airdate":"2011-04-26T12:00:00.000Z","category_id":15872,"game_id":3631}

**Comment by rysady** [comment]
Thanks @oddluck!  I'm actually making a fun little iOS trivia app with this!
