### ISSUE TITLE
jservice.io is down

### ISSUE THREAD

**Issue by Jerusus** [sottenad/jService#37]
http://jservice.io/ is down.

**Comment by sottenad** [comment]
It appears that something has gone haywire with heroku. I believe this might be the end of the line for this unless I can get it stood back up quickly. Thanks for letting me know.

**Comment by coolwanglu** [comment]
FWIW I was able to run it in my Docker container: https://github.com/coolwanglu/jservice-docker
Although I hope this repo will be updated for the latest ruby toolchain.

**Comment by Springboard-CourseDev** [comment]
@sottenad is there anything we can do to help get it back up?

**Comment by tylerclark** [comment]
@sottenad Do you have any update? As you can see from the user above ^ this site was being used for course work on Springboard so a bunch of students are impacted, including my son. Is it possible to clone and deploy somewhere else? I know Heroku can be a pain (I used to work at Salesforce). Perhaps Netlify or Firebase would work?

**Comment by sottenad** [comment]
I was unaware anyone was using this as a dependency to a real project. I'll take another look this evening, but in the few hours i've spent so far, upgrading to the latest modules has been a bear. In the mean time, if someone wants to host this somewhere else, I'm all for it and will help promote any alternatives if/when this comes back up. Unfortunately I have extremely limited bandwidth currently.

**Comment by Jerusus** [comment]
I've had success migrating my project to an API that also pulls from jarchive. The JSON structure is similar so it wasn't too much effort on my end, but I was only really using the "random question" functionality.

https://cluebase.readthedocs.io/en/latest/

http://cluebase.lukelav.in/clues/random

Compared to what jservice.io looked like before https://web.archive.org/web/20220624164517/http://jservice.io/

**Comment by sottenad** [comment]
I believe this will be up, at least the API portion, tonight

**Comment by tylerclark** [comment]
Awesome, thank u! Let me know if I can buy you a coffee or send you a tip! 👏
